// swift-tools-version: 6.0

import PackageDescription

// OpenLaunchpad's macOS UI is a two-process Xcode application:
// a short-lived Dock launcher plus an embedded LSUIElement agent.
//
// SwiftPM remains intentionally focused on the reusable/testable core modules.
// Build the application bundle with the Xcode project generated by XcodeGen.
let package = Package(
    name: "OpenLaunchpad",
    platforms: [
        .macOS(.v15),
    ],
    products: [
        .library(name: "AppCore", targets: ["AppCore"]),
        .library(name: "DisplayCore", targets: ["DisplayCore"]),
        .library(name: "LayoutCore", targets: ["LayoutCore"]),
    ],
    targets: [
        .target(name: "AppCore"),
        .target(name: "DisplayCore"),
        .target(name: "LayoutCore", dependencies: ["DisplayCore"]),
        .testTarget(name: "AppCoreTests", dependencies: ["AppCore"]),
        .testTarget(name: "DisplayCoreTests", dependencies: ["DisplayCore"]),
        .testTarget(
            name: "LayoutCoreTests",
            dependencies: ["DisplayCore", "LayoutCore"]
        ),
    ]
)
